### ISSUE TITLE
Security questions

### ISSUE THREAD

**Issue by bobi6666** [m1maker/NGT#13]
Hi, I have questions gameobject.ngtb must be with the exe file? if so isn't it dangerous? in my opinion, it should be included directly in the release exe, and it should be encrypted using aes or something like that, and I would initialize the aes myself when starting the game or in some other safe way, because at the moment it looks like this, if I saw the game like this, people would they could read both my data and file location

**Comment by DJ-Wolfy** [comment]
I don't understand how this would create anything more than a slight annoyance for anyone trying to decrypt your software

**Comment by bobi6666** [comment]
in this file is for example path to your folder contents of
initialized strings and some other data

2024-01-11 9:01 GMT+01:00, DJ-Wolfy ***@***.***>:
