### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by bobi6666** [m1maker/NGT#3]
Hello, I would like to summarize a few more issues
1.
if you initialize the timer t; and then you don't use restart but you give an alert and it will show you -2147472384
2. compiling executable doesn't work only in release/game_object.ngtb folder
3. I think that when calling the init engine, the 3d bass sound parameters should not be set or the bass shouldn't be initialized, because in the event that later there will be dll support and I want to implement my own sound system, I will have a problem
4. it would be good if the sdl2 library was implemented directly into the static exe file when creating the executable

**Comment by m1maker** [comment]
Hello. What do you meen compiling executable doesn't work only in release/game_object.ngtb folder

**Comment by bobi6666** [comment]
i mean i using win 11 and it does not make executable file run.bat in
the release folder

2023-12-24 22:45 GMT+01:00, m1maker ***@***.***>:

**Comment by bobi6666** [comment]
i also recommend you to use in your reg script
@="%ProgramFiles%\ngt\\NGTScript.exe \"%1\" -d"
that way if someone using windows on different drive than C: it will
automatically be redirected

2023-12-24 22:49 GMT+01:00, Peter Kubek ***@***.***>:

**Comment by bobi6666** [comment]
hello today i tried to compile ngt script and executable file is still
not created in the release folder. it works on windows 10 for some
people but on windows 11 not

2023-12-25 20:41 GMT+01:00, Peter Kubek ***@***.***>:

**Comment by m1maker** [comment]
Hello. I have Windows11 23H2 and everything works. Did I understand correctly that you do not have the run.exe file in the Release folder, but all other files, for example the object file game_object.ngtb, do exist?

**Comment by bobi6666** [comment]
yes not run.exe only gameobject.ngtb and also not any libs. i tried on my
win server 2016 with disabled uac and samething happen

Dňa st 3. 1. 2024, 7:56 m1maker ***@***.***> napísal(a):

**Comment by bobi6666** [comment]
hello i tried to do
            Compile(engine, "D:\\ngt\\game_object.ngtb");
            after i did that executable was created in the folder mentioned so it means that compiler on some computers needs to get information about current directory or something like that
