### ISSUE TITLE
a kritical problem with ngt's context menu registrations

### ISSUE THREAD

**Issue by peter1384** [m1maker/NGT#42]
hello. I've installed ngt, and then, when I pressed application on all my files which had .ngt extention, The open o option has been renamed to open with ngt, and when I uninstalled ngt, and then I pressed application on my files which had .ngt extention on them, the Open o option was gon from them, so now if i press application on any of my files with any extention such as .badBoy, .BadGirl, I have the open o option, but for .ngt files I don't have this option. What is wrong with ngt's registration of changing context menus up on uninstalation?

**Comment by m1maker** [comment]
Hello. Did you install NGTInstaller, or run NGT.reg in the main repository?

**Comment by peter1384** [comment]
ngt installer

**Comment by m1maker** [comment]
NGTInstaller was created by Harry. Write about it at:
https://github.com/harrymkt/ngt-includes
