### ISSUE TITLE
several ideas

### ISSUE THREAD

**Issue by harrymkt** [m1maker/NGT#6]
# several requests:

## random:

please make the random function to no limit on it.
for example, change below to double.
long random(long min, long max)
to
double random(double min, double max)

## scr class:

please make the screen reader class.
the class will hold the ability to speak, stop, and determine which screen reader is active.
for example, like bgt.
class screenreader
{
bool speak(int reader, string text);
bool is_active(int reader);
bool set_lib_path(string path);
}

## init engine:

please make the init_engine function to the ability to set the path of the dll files. for example
init_engine("libs");
this means the function will look dll files in libs/.

**Comment by bobi6666** [comment]
i am not sure if this random is ready for doubles because if you do: string rand=random(0,0.5);
now this does
1.26919
